// Generated by CoffeeScript 1.6.3
(function() {
  var fs, path;

  fs = require("fs");

  path = require("path");

  module.exports = function(basedir, allowedExtension) {
    return function(domain) {
      var basePath, data, files;
      basePath = path.normalize(basedir + '/' + domain);
      data = module.exports = {};
      files = fs.readdirSync(basePath);
      files.forEach(function(file) {
        var extension, fileName, filePath;
        extension = path.extname(file);
        fileName = path.basename(file, extension);
        if (extension !== ("." + allowedExtension)) {
          return;
        }
        filePath = basePath + "/" + fileName;
        console.log("Adding " + domain + " " + fileName + " " + extension);
        return data[fileName] = require(filePath);
      });
      return data;
    };
  };

}).call(this);
